@startuml
title Fluxo de "Consultar histórico de movimentações" (UC7)

start

:'Gerente' seleciona opção **"Histórico de Movimentações"** no dashboard;
:Sistema apresenta opções de filtro
(_por data, por produto, por tipo de evento_);
:'Gerente' seleciona os filtros desejados;
:Sistema consulta o banco de dados
com base nos filtros selecionados;
:Sistema exibe histórico de movimentações filtrado;

stop

@enduml
