@startuml
title Fluxo do Caso de Uso "Identificar produto via RFID" (UC1)

start
:Produto é adicionado ou removido da prateleira;
:Leitor RFID detecta a tag do produto;
:Leitor RFID captura o ID da tag;
:Microcontrolador (ESP32) recebe o ID da tag;
:Microcontrolador envia o ID da tag e o tipo de evento (adição/remoção) para o Backend;
stop

@enduml