@startuml
actor "Sistema de Prateleira Inteligente" as SPI <<Secundário>>
actor "Banco de Dados" as BD <<Secundário>>
actor "Dashboard" as Dashboard <<Secundário>>
actor "Gerente" as Gerente <<Primário>>
actor "Administrador" as Admin <<Primário>>

usecase "Detectar Alteração de Produto da Prateleira" as Detectar
usecase "Entrada de Produto" as Entrada
usecase "Saída de Produto" as Saida
usecase "Enviar Dados ao Banco de Dados" as Enviar
usecase "Receber informações do IoT" as ReceberIoT
usecase "Disponibilizar para o Dashboard" as DisponibilizarDashboard
usecase "Fazer Login" as FazerLogin
usecase "Consultar histórico de movimentações" as ConsultarHistorico
usecase "Visualizar status da prateleira" as VisualizarStatus
usecase "Visualizar alerta de produto acabando" as AlertaAcabando
usecase "Visualizar alerta de produto vencendo" as AlertaVencendo
usecase "Alterar quantidade de estoque manualmente" as AlterarEstoque

SPI --> Detectar
Detectar <|-- Entrada : <<extend>>
Detectar <|-- Saida : <<extend>>
Detectar --> Enviar : <<include>>

BD --> ReceberIoT
BD --> DisponibilizarDashboard

Gerente --> FazerLogin
FazerLogin <|-- ConsultarHistorico : <<extend>>
FazerLogin <|-- VisualizarStatus : <<extend>>
FazerLogin <|-- AlertaAcabando : <<extend>>
FazerLogin <|-- AlertaVencendo : <<extend>>
FazerLogin <|-- AlterarEstoque : <<extend>>

Dashboard --> ConsultarHistorico
Dashboard --> VisualizarStatus
Dashboard --> AlertaAcabando
Dashboard --> AlertaVencendo
Dashboard --> AlterarEstoque

Admin --> AlterarEstoque
@enduml