site_name: Documentação TCC

nav:
  - Home: index.md
  - Descrição Projeto: descrição_projeto.md
  - Regras de Negócio: regras_negocio.md
  - Requisitos funcionais e não funcionais: requisitos.md
  - Diagrama de casos de uso: descricao_casos_de_uso.md
  - Diagrama de atividade: atividade_uml.md

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode